spring.application.name=eureka-server

server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Ativar todos os endpoints do Actuator
management.endpoints.web.exposure.include=*

# Porta do Actuator
management.server.port=8084

# Prometheus endpoint
management.endpoint.prometheus.enabled=true